/*
 * AppImpExpManagement
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package ae.gov.mohap.odm.model.BiologicalDocuments;

/**
 * DrugStore
 */
import java.util.Date;
import java.util.Objects;
public class DrugStore {
	
  private String type = null;
  
  private String licenseNo = null;

  
  private String agentRegNo = null;

  
  private String agentName = null;

  
  private Date licenseExpireDate = null;
  
  private String licenseAuthority = null;

  public DrugStore licenseNo(String licenseNo) {
    this.licenseNo = licenseNo;
    return this;
  }

   /**
   * Get licenseNo
   * 
  **/
  
  public String getLicenseNo() {
    return licenseNo;
  }

  public void setLicenseNo(String licenseNo) {
    this.licenseNo = licenseNo;
  }

  public DrugStore agentRegNo(String agentRegNo) {
    this.agentRegNo = agentRegNo;
    return this;
  }

   /**
   * Get agentRegNo
   * 
  **/
  
  public String getAgentRegNo() {
    return agentRegNo;
  }

  public void setAgentRegNo(String agentRegNo) {
    this.agentRegNo = agentRegNo;
  }

  public DrugStore agentName(String agentName) {
    this.agentName = agentName;
    return this;
  }

   /**
   * Get agentName
   * 
  **/
  
  public String getAgentName() {
    return agentName;
  }

  public void setAgentName(String agentName) {
    this.agentName = agentName;
  }

  public DrugStore licenseExpireDate(Date licenseExpireDate) {
    this.licenseExpireDate = licenseExpireDate;
    return this;
  }

   /**
   * Get licenseExpireDate
   * 
  **/
  
  public Date getLicenseExpireDate() {
    return licenseExpireDate;
  }

  public void setLicenseExpireDate(Date licenseExpireDate) {
    this.licenseExpireDate = licenseExpireDate;
  }


  
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DrugStore drugStore = (DrugStore) o;
    return Objects.equals(this.licenseNo, drugStore.licenseNo) &&
        Objects.equals(this.agentRegNo, drugStore.agentRegNo) &&
        Objects.equals(this.agentName, drugStore.agentName) &&
        Objects.equals(this.licenseExpireDate, drugStore.licenseExpireDate) &&
        super.equals(o);
  }

  
  public int hashCode() {
    return Objects.hash(licenseNo, agentRegNo, agentName, licenseExpireDate, super.hashCode());
  }


  
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DrugStore {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    licenseNo: ").append(toIndentedString(licenseNo)).append("\n");
    sb.append("    agentRegNo: ").append(toIndentedString(agentRegNo)).append("\n");
    sb.append("    agentName: ").append(toIndentedString(agentName)).append("\n");
    sb.append("    licenseExpireDate: ").append(toIndentedString(licenseExpireDate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

/**
 * @return the type
 */
public String getType() {
	return type;
}

/**
 * @param type the type to set
 */
public void setType(String type) {
	this.type = type;
}

/**
 * @return the licenseAuthority
 */
public String getLicenseAuthority() {
	return licenseAuthority;
}

/**
 * @param licenseAuthority the licenseAuthority to set
 */
public void setLicenseAuthority(String licenseAuthority) {
	this.licenseAuthority = licenseAuthority;
}
  
}

