/*
 * AppImpExpManagement
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package ae.gov.mohap.odm.model.BiologicalDocuments;

import java.math.BigDecimal;
import java.util.Objects;
/**
 * InactiveIngredient
 */
public class InactiveIngredient {

	//Bio
  private Name name = null;
  
  //Bio
  private String indication = null;
  
  private BigDecimal quantity = null;

  
  private DicValue quantityUnit = null;

  
  private BigDecimal refQuantity = null;

  
  private DicValue refQuantityUnit = null;

  
  private Integer ipiId = null;

  
  private String functionDesc = null;

  
  private String additionalInfo = null;

  
  private String description = null;
  



public InactiveIngredient quantity(BigDecimal quantity) {
    this.quantity = quantity;
    return this;
  }

   /**
   * Get quantity
   * 
  **/
  
  public BigDecimal getQuantity() {
    return quantity;
  }

  public void setQuantity(BigDecimal quantity) {
    this.quantity = quantity;
  }

  public InactiveIngredient quantityUnit(DicValue quantityUnit) {
    this.quantityUnit = quantityUnit;
    return this;
  }

   /**
   * Get quantityUnit
   * 
  **/
  
  public DicValue getQuantityUnit() {
    return quantityUnit;
  }

  public void setQuantityUnit(DicValue quantityUnit) {
    this.quantityUnit = quantityUnit;
  }

  public InactiveIngredient refQuantity(BigDecimal refQuantity) {
    this.refQuantity = refQuantity;
    return this;
  }

   /**
   * Get refQuantity
   * 
  **/
  
  public BigDecimal getRefQuantity() {
    return refQuantity;
  }

  public void setRefQuantity(BigDecimal refQuantity) {
    this.refQuantity = refQuantity;
  }

  public InactiveIngredient refQuantityUnit(DicValue refQuantityUnit) {
    this.refQuantityUnit = refQuantityUnit;
    return this;
  }

   /**
   * Get refQuantityUnit
   * 
  **/
  
  public DicValue getRefQuantityUnit() {
    return refQuantityUnit;
  }

  public void setRefQuantityUnit(DicValue refQuantityUnit) {
    this.refQuantityUnit = refQuantityUnit;
  }

  public InactiveIngredient ipiId(Integer ipiId) {
    this.ipiId = ipiId;
    return this;
  }

   /**
   * Get ipiId
   * 
  **/
  
  public Integer getIpiId() {
    return ipiId;
  }

  public void setIpiId(Integer ipiId) {
    this.ipiId = ipiId;
  }

  public InactiveIngredient functionDesc(String functionDesc) {
    this.functionDesc = functionDesc;
    return this;
  }

   /**
   * Get functionDesc
   * 
  **/
  
  public String getFunctionDesc() {
    return functionDesc;
  }

  public void setFunctionDesc(String functionDesc) {
    this.functionDesc = functionDesc;
  }

  public InactiveIngredient additionalInfo(String additionalInfo) {
    this.additionalInfo = additionalInfo;
    return this;
  }

   /**
   * Get additionalInfo
   * 
  **/
  
  public String getAdditionalInfo() {
    return additionalInfo;
  }

  public void setAdditionalInfo(String additionalInfo) {
    this.additionalInfo = additionalInfo;
  }

  public InactiveIngredient description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * 
  **/
  
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }


  
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InactiveIngredient inactiveIngredient = (InactiveIngredient) o;
    return Objects.equals(this.quantity, inactiveIngredient.quantity) &&
        Objects.equals(this.quantityUnit, inactiveIngredient.quantityUnit) &&
        Objects.equals(this.refQuantity, inactiveIngredient.refQuantity) &&
        Objects.equals(this.refQuantityUnit, inactiveIngredient.refQuantityUnit) &&
        Objects.equals(this.ipiId, inactiveIngredient.ipiId) &&
        Objects.equals(this.functionDesc, inactiveIngredient.functionDesc) &&
        Objects.equals(this.additionalInfo, inactiveIngredient.additionalInfo) &&
        Objects.equals(this.description, inactiveIngredient.description) &&
        super.equals(o);
  }

  
  public int hashCode() {
    return Objects.hash(quantity, quantityUnit, refQuantity, refQuantityUnit, ipiId, functionDesc, additionalInfo, description, super.hashCode());
  }


  
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InactiveIngredient {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    quantity: ").append(toIndentedString(quantity)).append("\n");
    sb.append("    quantityUnit: ").append(toIndentedString(quantityUnit)).append("\n");
    sb.append("    refQuantity: ").append(toIndentedString(refQuantity)).append("\n");
    sb.append("    refQuantityUnit: ").append(toIndentedString(refQuantityUnit)).append("\n");
    sb.append("    ipiId: ").append(toIndentedString(ipiId)).append("\n");
    sb.append("    functionDesc: ").append(toIndentedString(functionDesc)).append("\n");
    sb.append("    additionalInfo: ").append(toIndentedString(additionalInfo)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

/**
 * @return the indication
 */
public String getIndication() {
	return indication;
}

/**
 * @param indication the indication to set
 */
public void setIndication(String indication) {
	this.indication = indication;
}

/**
 * @return the name
 */
public Name getName() {
	return name;
}

/**
 * @param name the name to set
 */
public void setName(Name name) {
	this.name = name;
}
  
}

